task: detection

num_classes: 2
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: '/media/herd-i/Local Disk/herdi/bcs_object_detection/dataset/lameness/'
    ann_file: '/media/herd-i/Local Disk/herdi/bcs_object_detection/dataset/lameness/instances_default.json'
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: '/media/herd-i/Local Disk/herdi/bcs_object_detection/dataset/lameness/'
    ann_file: '/media/herd-i/Local Disk/herdi/bcs_object_detection/dataset/lameness/instances_default.json'
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False